// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjy3xFyex5Jtfs7NaPl7KmxPNpgAtTaX8',
    appId: '1:744966174591:web:6363154985b3fe53f98c4a',
    messagingSenderId: '744966174591',
    projectId: 'direct-messaging-app',
    authDomain: 'direct-messaging-app.firebaseapp.com',
    storageBucket: 'direct-messaging-app.appspot.com',
    measurementId: 'G-3ZF0VD02M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtK09jYM5dyKT174JkiepuZmf4lX0mw60',
    appId: '1:744966174591:android:04520cd7cc800205f98c4a',
    messagingSenderId: '744966174591',
    projectId: 'direct-messaging-app',
    storageBucket: 'direct-messaging-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB97ZrwP_xJ0649ikaULGfSvzbBziciEds',
    appId: '1:744966174591:ios:7b65d9cdb8442692f98c4a',
    messagingSenderId: '744966174591',
    projectId: 'direct-messaging-app',
    storageBucket: 'direct-messaging-app.appspot.com',
    iosBundleId: 'com.badenb.dma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB97ZrwP_xJ0649ikaULGfSvzbBziciEds',
    appId: '1:744966174591:ios:7b65d9cdb8442692f98c4a',
    messagingSenderId: '744966174591',
    projectId: 'direct-messaging-app',
    storageBucket: 'direct-messaging-app.appspot.com',
    iosBundleId: 'com.badenb.dma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjy3xFyex5Jtfs7NaPl7KmxPNpgAtTaX8',
    appId: '1:744966174591:web:2435433d36f6ca30f98c4a',
    messagingSenderId: '744966174591',
    projectId: 'direct-messaging-app',
    authDomain: 'direct-messaging-app.firebaseapp.com',
    storageBucket: 'direct-messaging-app.appspot.com',
    measurementId: 'G-MSX9EE2SH5',
  );
}
